### ISSUE TITLE
GetQueueOne很慢，一次要1秒

### ISSUE THREAD

**Issue by GaoXiong666** [NewLifeX/NewLife.Redis.Core#1]
![YW_FC0BQC 5LU I~I ~D)J7](https://user-images.githubusercontent.com/53500372/201819478-0a0cb03f-54f5-455b-9004-8f85b9b0604e.png)

包是NewLife.Redis.Core 1.2.2022.1111,
每次取都要1秒左右，如果使用GetQueue就正常1ms，为什么？

**Comment by huguodong** [comment]
![image](https://user-images.githubusercontent.com/12368323/201839222-46e0339b-e00e-4426-8e6b-2f7850005a64.png)
我这里没问题

**Comment by GaoXiong666** [comment]
![image](https://user-images.githubusercontent.com/53500372/201840963-2450a3ce-f3a4-4224-8eee-0c29e839da2f.png)
![image](https://user-images.githubusercontent.com/53500372/201841372-a85da074-fdd4-4d98-ba93-5767af4ba1c5.png)

你那张图好像看不出来取每条消息所消耗的时间，我的疑问是为啥GetQueueOne这句话光执行就要1秒左右，跟GetQueue有很大的差别，你的意思是这是正常的吗？

**Comment by GaoXiong666** [comment]
![image](https://user-images.githubusercontent.com/53500372/201840963-2450a3ce-f3a4-4224-8eee-0c29e839da2f.png)
![image](https://user-images.githubusercontent.com/53500372/201841372-a85da074-fdd4-4d98-ba93-5767af4ba1c5.png)

你那张图好像看不出来取每条消息所消耗的时间，我的疑问是为啥GetQueueOne这句话光执行就要1秒左右，跟GetQueue有很大的差别，你的意思是这是正常的吗？

**Comment by huguodong** [comment]
![image](https://user-images.githubusercontent.com/12368323/201843258-376a2064-7ecd-46fc-9865-85fd9b54714d.png)
![image](https://user-images.githubusercontent.com/12368323/201843295-4f5a8729-3bef-46cf-bf73-7534e4269902.png)
![image](https://user-images.githubusercontent.com/12368323/201843323-68dbd2d9-a128-42e0-85c1-dbf2a41df793.png)

**Comment by huguodong** [comment]
是不是你的队列没有数据，你先插点数据进去呢
![image](https://user-images.githubusercontent.com/12368323/201843508-e2bbaa62-2927-425d-b59a-7d219493abb4.png)
![image](https://user-images.githubusercontent.com/12368323/201843577-ad1e9fdd-445f-4b71-bf9f-b3b1ae77a09d.png)

**Comment by GaoXiong666** [comment]
感谢，确实是没有数据的原因，但为何GetQueue不受有无数据的影响？

**Comment by huguodong** [comment]
看了源码，我设置了消息阻塞一秒钟.....,改成动态配置的吧

**Comment by huguodong** [comment]
如果不设置阻塞会报错

**Comment by huguodong** [comment]
已发布
