### ISSUE TITLE
 NewLife.Serialization.JsonHelper.ToJson 序列化decimal类型精度问题

### ISSUE THREAD

**Issue by GaoXiong666** [NewLifeX/NewLife.Redis.Core#2]
包版本 NewLife.Redis.Core  1.2.2022.1111
根据文档https://www.cnblogs.com/huguodong/p/16434717.html
5.2 实现可信队列部分，
我自己根据例子如下图添加队列
![UP7ENYZ)DMR6N)O(MHHN0XV](https://user-images.githubusercontent.com/53500372/201835843-17ec7c2a-a444-4018-a641-afd7f3bd5631.png)
其中
![image](https://user-images.githubusercontent.com/53500372/201835883-05eb73dc-8c1d-4b51-bb19-ff4c2b8c063e.png)
两个字段是decimal类型，如下图，添加时它自己序列化为两位小数
![image](https://user-images.githubusercontent.com/53500372/201836080-f6d1d82a-c7ff-4ab8-a2be-23a0e354c3a0.png)
但是如下图，用包里自带的ToJson()，会序列化为整数，导致这个消息清不掉
![image](https://user-images.githubusercontent.com/53500372/201836224-b6f3b9b1-e207-40e2-aa0d-258bd6ce1c23.png)

**Comment by huguodong** [comment]
现在推荐通过String获取，然后转成对应的实体,改成Getrxxxx<string>(xx)

**Comment by nnhy** [comment]
可信队列的确有这个问题，推荐按照String消费获取，然后原文确认。内部自己走json反序列化为对象。
