### ISSUE TITLE
.Net8 release

### ISSUE THREAD

**Issue by cirrussys** [NewLifeX/NewLife.Redis.Core#3]
Hi,

Thank you for this performant library!

As part of our .Net8 migration we're reviewing our dependencies. Do you plan to release a NewLife.Redis.Core targeting .Net 8.0 anytime soon?

Cheers

**Comment by Soar360** [comment]
If .NET 8.0 is released, we will upgrade it as soon as possible.

**Comment by huguodong** [comment]
now,support

**Comment by huguodong** [comment]
![image](https://github.com/NewLifeX/NewLife.Redis.Core/assets/12368323/e9e36a2c-1a8a-498d-87d2-ea91a9891369)
